CREATE TABLE [dbo].[ROLES_PAGES]
(
	[RoleId] INT NOT NULL, 
    [PageId] INT NOT NULL,
    CONSTRAINT [FK_ROLES_PAGES_RoleId_ROLES] FOREIGN KEY ([RoleId]) REFERENCES [ROLES]([Id]) ON DELETE CASCADE,
	CONSTRAINT [FK_ROLES_PAGES_PageId_PAGES] FOREIGN KEY ([PageId]) REFERENCES [USERS]([Id]) ON DELETE CASCADE,
)
