CREATE TABLE [dbo].[USERS_PAGES]
(
	[UserID] INT NOT NULL, 
    [PageId] INT NOT NULL, 
    CONSTRAINT [FK_USERS_PAGES_UserId_USERS] FOREIGN KEY ([UserID]) REFERENCES [USERS]([Id]),
    CONSTRAINT [FK_USERS_PAGES_PageId_PAGES] FOREIGN KEY ([PageID]) REFERENCES [PAGES]([Id])
)
